### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by MadhavJivrajani** [kt3k/license_checker#4]
Docker build fails saying the following:
```
Error: unzip is required to install Deno (see: https://github.com/denoland/deno_install#unzip-is-required).
The command '/bin/sh -c curl -fsSL https://deno.land/x/install/install.sh | sh' returned a non-zero code: 1
```

![Screenshot_20200805_154155](https://user-images.githubusercontent.com/12381034/89401003-4ab60180-d732-11ea-8ea0-df0963cf95e4.png)

**Comment by kt3k** [comment]
@MadhavJivrajani Thank you for reporting! Fixed the issue at #5. Please try the latest (v1.0.3) version.
