### ISSUE TITLE
License Checker 1.0.1 fails with "Error: unzip is required to install Deno"

### ISSUE THREAD

**Issue by Denubis** [kt3k/license_checker#7]
https://github.com/FAIMS/FAIMS3/runs/2691127168?check_suite_focus=true#step:2:441

Error is: "Error: unzip is required to install Deno (see: denoland/deno_install#unzip-is-required).
  The command '/bin/sh -c curl -fsSL deno.land/x/install/install.sh | sh' returned a non-zero code: 1
  "

(I'm getting ready to take that repo public, so the link should work... soon?)

**Comment by kt3k** [comment]
1.0.1 doesn't work anymore because Deno changed the release artifact from gzip to zip at some point. Please use the latest version v1.0.6. That should address the issue.

**Comment by Denubis** [comment]
Cool. (As an aside, your latest release is 1.0.1), will try with 1.0.6 and will report back.

**Comment by kt3k** [comment]
> As an aside, your latest release is 1.0.1

Ah, thanks! I didn't realize it. Just released v1.0.6 https://github.com/kt3k/license_checker/releases/tag/v1.0.6

**Comment by Denubis** [comment]
Resolved, that fixed everything. Thanks much!
